// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzHqRKq7Lj7ZRKDKnttxSUaZCNP_Q0tR4',
    appId: '1:764541534831:web:ae8b4a57cb1493e23c039a',
    messagingSenderId: '764541534831',
    projectId: 'handshake-9eba6',
    authDomain: 'handshake-9eba6.firebaseapp.com',
    storageBucket: 'handshake-9eba6.firebasestorage.app',
    measurementId: 'G-Z7SZ64TDYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5le8zlHgJmOBj3qTVu_gLyYDF8aM-VY',
    appId: '1:764541534831:android:658211ec82a4d25f3c039a',
    messagingSenderId: '764541534831',
    projectId: 'handshake-9eba6',
    storageBucket: 'handshake-9eba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEylEhAd_yf4kW1yKYQJj2cw3vWe6_gs4',
    appId: '1:764541534831:ios:526f8093d77e37063c039a',
    messagingSenderId: '764541534831',
    projectId: 'handshake-9eba6',
    storageBucket: 'handshake-9eba6.firebasestorage.app',
    iosBundleId: 'com.example.theHandshake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEylEhAd_yf4kW1yKYQJj2cw3vWe6_gs4',
    appId: '1:764541534831:ios:526f8093d77e37063c039a',
    messagingSenderId: '764541534831',
    projectId: 'handshake-9eba6',
    storageBucket: 'handshake-9eba6.firebasestorage.app',
    iosBundleId: 'com.example.theHandshake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzHqRKq7Lj7ZRKDKnttxSUaZCNP_Q0tR4',
    appId: '1:764541534831:web:fa86bc2f7ffeba253c039a',
    messagingSenderId: '764541534831',
    projectId: 'handshake-9eba6',
    authDomain: 'handshake-9eba6.firebaseapp.com',
    storageBucket: 'handshake-9eba6.firebasestorage.app',
    measurementId: 'G-QEJ44T8Z46',
  );

}